<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	<WindowsPackageType>None</WindowsPackageType>
	<WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
	<PublishSingleFile>true</PublishSingleFile>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.22000.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>FramesToMMSpriteResources</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x64</Platforms>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <PublishProfile>win-$(Platform).pubxml</PublishProfile>
    <UseWinUI>true</UseWinUI>
    <EnableMsixTooling>false</EnableMsixTooling>
    <Nullable>enable</Nullable>
    <SelfContained>true</SelfContained>
    <LangVersion>13.0</LangVersion>
    <EnableMsixTooling>true</EnableMsixTooling>
	<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>
  <ItemGroup>
    <Page Remove="ColorPanel.xaml" />
    <Page Remove="Controls\CardGroup.xaml" />
    <Page Remove="Styles.xaml" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Assets\Tools\oxipng.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Content Include="Assets\SplashScreen.scale-200.png" />
    <Content Include="Assets\LockScreenLogo.scale-200.png" />
    <Content Include="Assets\Square150x150Logo.scale-200.png" />
    <Content Include="Assets\Square44x44Logo.scale-200.png" />
    <Content Include="Assets\Square44x44Logo.targetsize-24_altform-unplated.png" />
    <Content Include="Assets\Wide310x150Logo.scale-200.png" />
  </ItemGroup>
  <ItemGroup>
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>
  <!--
    Defining the "Msix" ProjectCapability here allows the Single-project MSIX Packaging
    Tools extension to be activated for this project even if the Windows App SDK Nuget
    package has not yet been restored.
  -->
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.WinUI.Controls.Primitives" Version="8.2.251219" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.2526" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.3.1" />
    <PackageReference Include="SkiaSharp" Version="4.150.1" />
    <PackageReference Include="SkiaSharp.Views.WinUI" Version="3.119.2" />
    <PackageReference Include="System.Windows.Extensions" Version="10.0.10" />
  </ItemGroup>
  <ItemGroup>
    <None Update="ColorPanel.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Controls\CardGroup.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Styles.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
  </ItemGroup>
  <!--
    Defining the "HasPackageAndPublishMenuAddedByProject" property here allows the Solution
    Explorer "Package and Publish" context menu entry to be enabled for this project even if
    the Windows App SDK Nuget package has not yet been restored.
  -->
  <!-- Publish Properties -->
  <PropertyGroup>
    <PublishReadyToRun Condition="'$(Configuration)' == 'Debug'">False</PublishReadyToRun>
    <PublishReadyToRun Condition="'$(Configuration)' != 'Debug'">True</PublishReadyToRun>
    <PublishTrimmed Condition="'$(Configuration)' == 'Debug'">False</PublishTrimmed>
    <PublishTrimmed Condition="'$(Configuration)' != 'Debug'">True</PublishTrimmed>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>   
  </PropertyGroup>
  <ItemGroup>
    <TrimmerRootDescriptor Include="ILLink.Descriptors.xml" />
  </ItemGroup>
</Project>